name: inpole_env

channels:
- pytorch
- conda-forge
- nodefaults

dependencies:
- python=3.10.8
- mamba
- pip
- poetry=1.6.1
- pytorch::pytorch=1.12.1
- pip:
  # Installation with Poetry fails.
  - -e ../risk-slim
