#!/usr/bin/env bash
#SBATCH -A <ACCOUNT>
#SBATCH -p alvis
#SBATCH -N 1
#SBATCH --gpus-per-node=<GPU>:1
#SBATCH -t 0-1:0  # days-hours:minutes
#SBATCH --output=<EXPERIMENT_PATH>/logs/%x_%j.out

experiment='<EXPERIMENT>'
experiment_path='<EXPERIMENT_PATH>'
container_path='<CONTAINER_PATH>'

cd ~
rsync -r inpole $TMPDIR --exclude='*_env'
cd $TMPDIR/inpole

module purge
apptainer exec --nv $container_path python scripts/collect_results.py \
  --experiment $experiment --experiment_path $experiment_path
