#!/usr/bin/env bash
#SBATCH -A <ACCOUNT>
#SBATCH -p alvis
#SBATCH -N 1
#SBATCH --gpus-per-node=<GPU>:1
#SBATCH -t 5-0:0  # days-hours:minutes
#SBATCH --output=<EXPERIMENT_PATH>/logs/%x_%A_%a.out

experiment_path='<EXPERIMENT_PATH>'
estimator='<ESTIMATOR>'
container_path='<CONTAINER_PATH>'

if [ -z $SLURM_ARRAY_TASK_ID ]
then
  config_number='001'
else
  config_number=$(printf '%03d' $SLURM_ARRAY_TASK_ID)
fi
config_path=${experiment_path}/configs/${estimator}/config${config_number}.yaml

cd ~
cp -r inpole $TMPDIR
cd $TMPDIR/inpole

module purge
apptainer exec --nv $container_path python scripts/train_predict.py \
  --config_path $container_path --estimator $estimator
