experiment: ra

results:
  path: results/ra
  sort_by: accuracy

metrics:
- accuracy
- auc:
    average: macro
- auc: 
    average: null
- ece
- sce

data:
  path: data/ra/data.pkl
  valid_size: 0.2
  test_size: 0.2
  seed: 0

estimators:
  seed: 0
  # Estimator-specific parameters can be specified here.
  sdt:
    grow_incrementally: false  # Fit a fixed-size tree.
  pronet:
    module__num_prototypes: 10  # Use 10 prototypes.

hparams:
  seed: 0
