experiment: ra

results:
  path: /mimer/NOBACKUP/groups/inpole/results/ra
  sort_by: auc

metrics:
- accuracy
- balanced_accuracy
- auc:
    average: weighted
- auc:
    average: null
- ece
- sce

data:
  path: /mimer/NOBACKUP/groups/inpole/data/ra_Xgy_0831.pkl
  valid_size: 0.2
  test_size: 0.2
  seed: 0
  sample_size: null
  include_context_variables: true
  include_previous_treatment: true
  fillna_value: csDMARD therapy
  aggregate_history: true
  reduction: 'max'
  add_current_context: true
  aggregate_exclude: &exclude
  - stage
  - year
  - age
  - gender
  - college_completed
  - work_status
  - insurance_private
  - insurance_medicare
  - insurance_medicaid
  - insurance_none
  - duration_ra
  shift_periods: 1
  shift_exclude: *exclude

estimators:
  seed: 0
  rdt:
    module__prediction: max
  truncated_rdt:
    module__prediction: max
  dt:
    num_ccp_alphas: 10

hparams:
  seed: 0
